### ISSUE TITLE
Is O3DS emuNAND downgrade available on GW mode?

### ISSUE THREAD

**Issue by MelonGx** [Plailect/OTP#4]
If yes, then this OTP guide can also be used on fixing O3DS JPN frankenfirmwares from 7.0.0-2J to 8.1.0-6J.

7.0.0-2J ~ 8.1.0-6J are very special.
They can't be booted by DS Profile exploit because they don't have a valid MSET.
They can't be booted by CFW URL because CFW URL don't support -2J ~ -6J Browser.
They can't be upgraded to 9.0-9.2 since no 9.0-9.2 JPN carts exist.
They can only be booted by GW URL.

**Comment by Plailect** [comment]
So, if I'm understanding the issue correctly, you have no entrypoints other than Gateway's browserhax and you don't want to update to 10.5? If that's true, then I can think of two different solutions. (Neither of them related to this guide since 2xrsa only works on 2.1)

 + Using [dukesrg's Gateway launcher](http://dukesrg.no-ip.org/3ds/go.html) to launch [Decrypt9WIP](https://github.com/d0k3/Decrypt9WIP/releases)'s Launcher.dat (which is included in every release), dumping your CTR NAND, then copying the [update CIAs](https://mega.nz/#!NtswiSDJ!sWvpVP4yWL_H66sOMG9VCJh3xMGG0_GgaX22gTpRE24) manually into CTR NAND, then flashing back to sysNAND (this is super risky and more research would need to be done.

*OR*

 + Getting a working version of sysUpdater converted into a Launcher.dat and updating to 9.2 using the update files [here](https://mega.nz/#!NtswiSDJ!sWvpVP4yWL_H66sOMG9VCJh3xMGG0_GgaX22gTpRE24).

**Comment by fox8091** [comment]
Do an update to 10.3 using sysUpdater, and then downgrade.

**Comment by Plailect** [comment]
Note that @fox8091's solution will only work if you have a Gateway flashcart, not through the gateway URL.

**Comment by Plailect** [comment]
@fox8091's solution could also work. You'd need to follow [this](https://gbatemp.net/threads/402236/) to inject FBI into Health and Safety. From there you can, using Gateway's Launcher.dat and web entry point, launch sysNAND with signature checks patched out. You could then install the [sysUpdater](https://github.com/profi200/sysUpdater/releases) CIA and use that to **update** sysNAND to 9.2 using [these](https://mega.nz/#!NtswiSDJ!sWvpVP4yWL_H66sOMG9VCJh3xMGG0_GgaX22gTpRE24) files. **If you downgrade while in Gateway mode you will brick!**

**Comment by MelonGx** [comment]
I doubt if the 10.3 solution workable, since
- Sysupdater + GW mode = Brick
- 7.0.0-2J ~ 8.1.0-6J have only GW access

GW launcher launching Decrypt9 is untested. I'll ask those frankenfirmware owners to test it.
rxTools 2.X web entrypoint, which is non-CakeHax, considered as a possibly bootable entrypoint, has been tested failed.
CakeHax related CFW entrypoints have proved unsupported -2 to -6 Browsers.

**Comment by Plailect** [comment]
I have been told the latest version of sysUpdater can work for an update
(if not a downgrade) in GW but you'd need to test that with a hardmodded
console first to make sure.
